apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  labels:
    app.kubernetes.io/name: nodejs-server
    app.kubernetes.io/instance: nodejs-server-westindia
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: MERN_App
    app.kubernetes.io/managed-by: Azure_Kubernetes_Service
spec:
  selector:
    matchLabels:
      app: nodejs-server
  replicas: 3
  nodeSelector:
    labels:
      "kubernetes.io/os": linux
      "topology.kubernetes.io/region": westus
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
  template:
    metadata:
      labels:
        app: nodejs-server
    spec:
      containers:
      - name: nodejs-container
        image: articles.azurecr.io/k8s/app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        envFrom:
          - secretRef: 
              name: my-secret
        resources:
          requests:
            cpu: 100m
            memory: 400Mi
          limits:
            cpu: "1"
            memory: 600Mi
        # Can be used to check if database connection has been established
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-server
  labels:
    app.kubernetes.io/name: nodejs-server
    app.kubernetes.io/instance: nodejs-server-westindia
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: MERN_App
    app.kubernetes.io/managed-by: Azure_Kubernetes_Service
spec:
  selector:
    app: nodejs-server
  type: LoadBalancer
  ports:
  - protocol: TCP
    appProtocol: 'kubernetes.io/h2c'
    port: 80
    targetPort: http