name: Dockerize and deploy using ACR and ACA
on:
  push:
    branches:
      - save4
jobs:
  Build:
    name: Azure-Build-and-Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Azure
        uses: azure/login@v2 
        with:    
          creds: ${{ secrets.AZURE_CREDENTIALS_A }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: articles.azurecr.io/github/app
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      # - name: Build and deploy Container App
      #   uses: azure/container-apps-deploy-action@v1
      #   with:
      #     appSourcePath: ${{ github.workspace }}
      #     acrName: articles
      #     imageToBuild: articles.azurecr.io/github/app
      #     containerAppName: articles
      #     resourceGroup: showcase