name: Dockerize and deploy using ACR and ACA
on:
  push:
    branches:
      - production
    paths-ignore:
      - '**/*.md'
jobs:
  Build:
    name: Azure-Build-and-Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Azure
        uses: azure/login@v2 
        with:    
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}
          acrName: articles
          imageToBuild: articles.azurecr.io/github/app
          containerAppName: articles
          resourceGroup: showcase