  name: Dockerize and push to AWS ECR
  on:
    push:
      branches:
        - save4
  jobs:
    Build:
      name: Build
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        # - name: view the secrets context
        #   shell: bash
        #   run: echo "$SECRETS_CONTEXT"
        #   env:
        #     SECRETS_CONTEXT: ${{ toJson(secrets) }}

        - name: Configure AWS credentials 
          uses: aws-actions/configure-aws-credentials@v1
          with: 
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
            aws-region: ${{ vars.AWS_REGION }}
        
        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1

        - name: Build, tag, and push the image to Amazon ECR
          id: build-image
          env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
          run: |
            docker build -t $ECR_REGISTRY/$ECR_REPOSITORY .
            docker push $ECR_REGISTRY/$ECR_REPOSITORY